In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
import pandas as pd
import glob
import numpy as np

In [ ]:
loc = '/content/gdrive/Shared drives/HLA/results/hlaforest/d3/'
df = pd.DataFrame()

In [ ]:
with open(loc+'/accession/d1_list.txt') as f:
  accessionnumbers = f.readlines()

In [ ]:
ERR,A1,A2,B1,B2,C1,C2 = list(), list(), list(), list(), list(), list(), list()

In [ ]:
for number in accessionnumbers: 
  print (number)
  # creating the path to the sample
  formatted_num = number.rstrip('\n')
  path = f"{loc}/{formatted_num}/haplotypes.txt"

  try:
    import csv
    limit = 0
    sample = list()
    with open(path) as bookfile:
      for line in bookfile:
        limit = limit +1
        if limit < 7:
          fields= line.split("\t")
          sample.append(fields[2][7:])
      #print(sample[1])
      ERR.append(number)
      A1.append(sample[0])
      A2.append(sample[1])
      B1.append(sample[2])
      B2.append(sample[3])
      C1.append(sample[4])
      C2.append(sample[5])

  except FileNotFoundError:
    pass
  except IndexError:
    pass

ERR009159

ERR009168

ERR009154

ERR009147

ERR009133

ERR009146

ERR009167

ERR009097

ERR009124

ERR009122

ERR009140

ERR009096

ERR009109

ERR009142

ERR009135

ERR009166

ERR009149

ERR009119

ERR009103

ERR009141

ERR009108

ERR009121

ERR009139

ERR009155

ERR009123

ERR009163

ERR009157

ERR009113

ERR009117

ERR009129

ERR009115

ERR009136

ERR009144

ERR009107

ERR009118

ERR009164

ERR009137

ERR009132

ERR009130

ERR009106

ERR009156

ERR009152

ERR009104

ERR009114

ERR009134

ERR009151

ERR009099

ERR009111

ERR009145

ERR009105

In [ ]:
for i in range(len(ERR)):
  ERR[i] = ERR[i].strip()
converted_list1=[]
for i in A1:
  converted_list1.append(i.strip())
converted_list2=[]
for i in A2:
  converted_list2.append(i.strip())
converted_list3=[]
for i in B1:
  converted_list3.append(i.strip())
converted_list4=[]
for i in B2:
  converted_list4.append(i.strip())
converted_list5=[]
for i in C1:
  converted_list5.append(i.strip())
converted_list6=[]
for i in C2:
  converted_list6.append(i.strip())

In [ ]:
dfERR = pd.DataFrame(ERR)
dfA1 = pd.DataFrame(converted_list1)
dfA2 = pd.DataFrame(converted_list2)
dfB1 = pd.DataFrame(converted_list3)
dfB2 = pd.DataFrame(converted_list4)
dfC1 = pd.DataFrame(converted_list5)
dfC2 = pd.DataFrame(converted_list6)

In [ ]:
df=pd.DataFrame(np.column_stack([ERR,converted_list1,converted_list2,converted_list3,converted_list4,converted_list5,converted_list6]), 
                               columns=['ERR','A', 'A.1','B','B.1','C','C.1'])

In [ ]:
for col in df.columns[df.columns!='ERR']:
    if '.' in col:
        allele = col.split('.')[0]
        for i in range(len(df[col])):
              df[col][i]=allele+'*'+ df[col][i]
    else: 
        for i in range(len(df[col])):
              df[col][i]=col+'*'+ df[col][i]

In [ ]:
df

          ERR         A      A.1          B      B.1        C      C.1
0   ERR009159   A*02:01  A*03:01    B*07:02  B*57:01  C*07:02  C*06:02
1   ERR009168   A*02:01  A*32:01    B*40:02  B*08:01  C*07:02  C*02:02
2   ERR009154   A*02:01  A*68:01    B*40:01  B*44:02  C*07:04  C*03:04
3   ERR009147   A*02:01  A*68:01    B*07:02  B*15:01  C*07:02  C*03:04
4   ERR009133   A*03:01  A*03:01    B*35:01  B*35:01  C*04:01  C*04:01
5   ERR009146   A*26:01  A*30:02    B*44:02  B*18:01  C*05:01  C*05:01
6   ERR009167   A*24:02  A*01:01    B*08:01  B*39:01  C*07:02  C*07:02
7   ERR009097   A*03:01  A*25:01    B*08:01  B*18:01  C*07:02  C*12:03
8   ERR009124   A*24:02  A*01:01    B*40:01  B*08:01  C*07:02  C*03:04
9   ERR009122   A*02:01  A*02:01    B*15:01  B*44:02  C*03:04  C*05:01
10  ERR009140   A*02:01  A*02:01    B*14:02  B*14:01  C*08:01  C*08:01
11  ERR009096   A*03:01  A*01:01    B*07:02  B*07:02  C*07:02  C*07:02
12  ERR009109   A*02:01  A*32:01    B*40:02  B*27:05  C*07:04  C*02:02
13  ERR009142   A*02:01  A*02:01    B*27:05  B*57:01  C*06:02  C*02:02
14  ERR009135   A*03:01  A*26:01    B*07:02  B*07:02  C*07:02  C*07:02
15  ERR009166   A*01:01  A*02:01    B*07:02  B*07:02  C*07:50  C*05:01
16  ERR009149   A*02:01  A*02:01    B*44:02  B*55:01  C*03:04  C*05:01
17  ERR009119   A*02:01  A*01:01    B*35:31  B*08:01  C*07:02  C*04:01
18  ERR009103   A*29:02  A*26:01    B*44:02  B*44:02  C*05:01  C*07:02
19  ERR009141   A*11:01  A*01:01    B*07:02  B*51:01  C*07:02  C*15:13
20  ERR009108   A*01:01  A*01:01    B*08:01  B*57:03  C*07:01  C*06:02
21  ERR009121   A*02:01  A*02:01    B*08:01  B*13:02  C*07:01  C*06:02
22  ERR009139   A*24:02  A*03:01    B*07:02  B*07:02  C*07:02  C*07:02
23  ERR009155   A*02:01  A*29:02    B*07:02  B*27:05  C*07:02  C*01:02
24  ERR009123   A*11:01  A*24:02    B*15:01  B*18:01  C*07:02  C*03:04
25  ERR009163  A*02:135  A*02:65    B*35:35  B*35:31  C*04:01  C*12:03
26  ERR009157   A*02:01  A*01:01    B*07:02  B*07:02  C*07:02  C*07:02
27  ERR009113   A*02:01  A*11:01    B*35:01  B*44:02  C*04:01  C*05:01
28  ERR009117   A*02:01  A*03:01    B*35:01  B*35:31  C*07:04  C*04:01
29  ERR009129   A*31:01  A*01:01    B*40:01  B*08:01  C*07:01  C*03:04
30  ERR009115   A*02:01  A*01:01    B*08:01  B*44:02  C*07:02  C*05:01
31  ERR009136   A*11:01  A*01:01    B*51:01  B*51:01  C*15:05  C*07:41
32  ERR009144   A*11:01  A*32:01    B*40:02  B*44:02  C*15:05  C*16:01
33  ERR009107   A*02:01  A*25:01    B*40:01  B*44:02  C*05:01  C*03:04
34  ERR009118   A*02:01  A*02:01  B*44:138Q  B*44:18  C*07:02  C*05:01
35  ERR009164   A*02:01  A*01:01    B*07:02  B*08:01  C*07:02  C*07:02
36  ERR009137   A*02:01  A*31:01    B*07:02  B*15:01  C*07:02  C*03:04
37  ERR009132   A*02:01  A*01:01    B*07:02  B*07:02  C*07:02  C*07:02
38  ERR009130   A*24:02  A*24:02    B*51:01  B*44:02  C*04:01  C*03:04
39  ERR009106   A*24:02  A*01:01    B*07:02  B*08:01  C*07:01  C*07:01
40  ERR009156   A*02:01  A*02:01    B*51:01  B*44:02  C*05:01  C*14:02
41  ERR009152   A*03:01  A*01:01    B*07:02  B*07:02  C*07:02  C*07:02
42  ERR009104   A*02:01  A*02:01    B*44:02  B*44:02  C*05:01  C*05:03
43  ERR009114   A*24:02  A*29:02    B*44:03  B*57:03  C*06:02  C*16:01
44  ERR009134   A*02:01  A*03:01    B*07:02  B*07:02  C*07:02  C*07:02
45  ERR009151   A*24:02  A*03:01    B*07:02  B*07:02  C*07:02  C*07:02
46  ERR009099   A*03:01  A*01:01    B*08:01  B*14:02  C*07:01  C*08:01
47  ERR009111   A*24:02  A*03:01    B*07:02  B*07:02  C*07:02  C*07:02
48  ERR009145   A*02:01  A*24:02    B*35:01  B*35:01  C*04:01  C*03:04
49  ERR009105   A*24:02  A*01:01    B*07:02  B*08:01  C*07:02  C*07:02

In [ ]:
df.to_csv('hlaforest_d1.csv', index=False)
! cp hlaforest_d1.csv "/content/gdrive/MyDrive/hlaforest_d1/d1results"